# Hello World In Tensorflow

We start of our journey by first providing a simple hello word program using tensorflow. This will will be followed by a discussion of the tensor flow paradigms which will help us understand this simple program. 

To use tensorflow we should import it:


In [2]:
import tensorflow as tf # This gives access to tensorflow libraries. Note that  Tensorflow was installed in a python2.7  
                        # environment in anaconda

The Hello word program Example. This is our first program!


In [3]:
helloworld = tf.constant('Hello, world!') # constant varirable declaration

with tf.Session() as sess:      # create a session
    print(sess.run(helloworld)) #print output of running the the constant c in a ssession


Hello, world!


# Tensorflow mechanisms and Paradigms

There are 3 main concept to undrstand while using tensorflow:
    1. Tensors
    2. Operations
    3. Graphs (also known as 'Computational graph' or 'Datagraph')
    4. Sessions

<p><b>Tensors: </b>Are arrays of arbitrary dimensionality and tensorflow actually gets its name from "tensors". . Tensors can be of any arbitrary dimensionality but most times we will often work with simpler dimensions. These dimensions can either be <i>static type</i> or  <i>dynamic</i>. Typical dimensions we will be working with are:
The rank in the table below is the dimension of the tensor.
<p> </p>
        <table width = "100%">
        <tr>
    <th>Ranks</th><th>Math Entity</th><th>Python Example</th>
      </tr>
     <tr>
      <td>0</td><td>Scalar (0-d array)</td> <td> "Hello world" or 5</td>
      </tr>
      <tr><td>1</td><td>Vector (1-d array)</td> <td>[1, 2, 3]</td>
      </tr>
       <tr><td>2</td><td>Matrix (2-d array)</td> <td>m = [  [1.1, 2.1, 3.1], [4.2, 9, 6], [10, 8, 67]  ]</td>
      </tr> 
        
        </table>


 </p>

<p><b>Operations: </b> The tensor flow operations create, manipulate or destroy tensors which are fed into it.</p>
<p><b>Graphs: </b> This is a typical graph data structure. A typical tensorflow program consist of one or more of these graphs. The critical principle in tensorflow -as far as we are concerned- is:
    <ul style="list-style-type:disc" >
      <li> A graph's nodes are operations; a graph's edges are tensors.</li>
      <li> Tensors flow through the graph, and are manipulated at each node by the operations.</li>
      <li> The output tensor of one operation often becomes the input tensor to a subsequent operation. </li>
      <li>nodes are only computed when needed, based on the needs of associated nodes</li>
      <li>Graphs should run within a TensorFlow session.</li>
    </ul>  
    
 
</p>
</p><b>Sessions: </b>  A session holds all  the state for the graph(s) it runs. In addition, a session can distribute graph execution across multiple machines (assuming the program is run on some distributed computation framework).</p>

#### Using the hello program as an example, can we identify the session, graph and tensor? 

<p><b>Other Important Concepts</b></p>
<p><b>Variables/Constants</b> Tensors can be stored in the graph as <i>constants</i> or <i>variables</i>. Constants hold tensors whose values can't change, while variables hold tensors whose values can change. However, constants and variables are  <i>operations in the graph</i>. A constant is an operation that always returns the same tensor value. A variable is an operation that will return whichever tensor it has been assigned to.



To define a <b> constant</b> use the "tf.constant" operator (since constant is an operation) and pass in its value. Note that a constant can either scalar or of multidimensions  as the examples below will show:

 

In [44]:
helloworld = tf.constant("hello world");
constant_Value = tf.constant(5) # Scalar. Note absence of square brackets. This is a Scalar Constant
  

In [45]:
#Note the shape . A scalar constant indeed!
print(constant_Value) # we can also use print(x.get_shape)

Tensor("Const_28:0", shape=(), dtype=int32)


Note the square bracket in the examples below. Use the square brackets when you want 1,2,3.. Dimensions and not a scalar.

In [46]:
#Lets change the constant:
constant_Value_2 =  tf.constant([5])
constant_value_3 = tf.constant([5,4,5])
print(constant_Value_2.shape) # we can use consatant_value_2.shape too as illutrated here.
print(constant_Value_2)      
print(constant_Value_2.get_shape)# Note the constant is now a 1 d - that is a vector
print(constant_value_3)# the shape is still 1 d - a vector. Observe the same thing for examples on variables.
                       #Constant_value_2 and _3 are of same dimension. See note on variable on how to 
                       # read this

(1,)
Tensor("Const_29:0", shape=(1,), dtype=int32)
<bound method Tensor.get_shape of <tf.Tensor 'Const_29:0' shape=(1,) dtype=int32>>
Tensor("Const_30:0", shape=(3,), dtype=int32)


In [30]:
constant_Value_4 =  tf.constant([[5,3,5],[2,3,5]])
print(constant_Value_4)      
print(constant_Value_4.get_shape)# Note the constant is now a 2 d - matrix


(2, 3)
Tensor("Const_21:0", shape=(2, 3), dtype=int32)
<bound method Tensor.get_shape of <tf.Tensor 'Const_21:0' shape=(2, 3) dtype=int32>>


Similarly, for a variable we have:
 
 


In [41]:
y = tf.Variable([5]) 
#Or you can create the variable first and assign a value later 
#like this (note that you always have to specify a default value):
y = tf.Variable([0]) # specify default value
y = y.assign([10])


In [42]:
# Now look at the examplw below. The first print shows that y is a tensfor flow object 
# (its type) and it still not a tensorflow program until we run it in a session. 
# when run in a session so that  we see that the value we expected was returned.  
# we might expect - the value we assigned.

In [43]:
print(y)
with tf.Session() as sess:     
    print(sess.run(y))

Tensor("Assign_3:0", shape=(1,), dtype=int32_ref)
[10]


<i>Note the shape that was returned above.</i> We proceed with two more examples: Note the change in shape for the example below. There is a subtle difference between this and the mathematical notion of dimension. In particular for the  example below:
<p><i>Read the shape as vector with 2 elements and since it is a vector it is ONE DIMENSION - verify this from table above.</i></p>  

In [35]:
y = tf.Variable([2,3]) # specify default value
y = y.assign([2,3])
print(y)
with tf.Session() as sess:     
    print(sess.run(y))
    


Tensor("Assign_7:0", shape=(2,), dtype=int32_ref)
[2 3]


In [37]:
y = tf.Variable([[2,3],[2,1]]) # specify default value
y = y.assign([[2,3],[4,5]])
print(y)
with tf.Session() as sess:     
    print(sess.run(y))

Tensor("Assign_9:0", shape=(2, 2), dtype=int32_ref)
[[2 3]
 [4 5]]


The output above is a matrix of 4 elements. It is <i>Two dimensional</i>.

In [42]:
y = tf.Variable([[2,3,4],[2,1,2]]) # specify default value
y = y.assign([[2,3,4],[4,5,3]])
print(y)
with tf.Session() as sess:     
    print(sess.run(y))

Tensor("Assign_12:0", shape=(2, 3), dtype=int32_ref)
[[2 3 4]
 [4 5 3]]


Care must be taken to monitor the dimensions. As this will always be a source of error and can lead to incompatible operations.
Try using [2,3] , [1,2,5] as assigned values and observe the errors


<p>We can combine the  constants and/or the variables,with other operations like "tf.subtract". 

<p>On evaluating the tf.subtract operation, it will call your tf.constant or 
tf.Variable operations to get their values and then return a new tensor with the difference of the values.
 </p>
<p>It should be noted that, for tf.Variables we  must explicitly initialize all variables by creating a
<b>tf.initialize_all_variables </b> operation and calling it at the start of your session.</p></p>