# Diving a little deeper into Tensorflow

<p>In this session we provide a more explanation on how to use tensorflow variables and perform operations on them.  </p>

<p><b>TENSORS AND THEIR SHAPES </b></p>

<p>Shapes  characterize the <b>size</b> and <b>number of dimensions</b> of a tensor. The shape of a tensor is expressed as <i>list</i>, and  the ith element  of the list is size along dimension i. The length of the list  indicates the rank of the tensor (i.e., the number of dimensions).</p>

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt # for visualization.
import numpy as np              # Low-level numerical Python library.
import pandas as pd             # Higher-level numerical Python library.

In [5]:
with tf.Graph().as_default():
    # A scalar is a 0-D tensor.
    scalar = tf.zeros([])

    # A vector with 3 elements.
    vector = tf.zeros([3])

    # A matrix with 2 rows and 3 columns.
    matrix = tf.zeros([2, 3])

    with tf.Session() as sess:
        print 'scalar of shape', scalar.get_shape(), 'and value:\n', scalar.eval()
        print 'vector of shape', vector.get_shape(), 'and value:\n', vector.eval()
        print 'matrix of shape', matrix.get_shape(), 'and value:\n', matrix.eval()


 scalar of shape () and value:
0.0
vector of shape (3,) and value:
[ 0.  0.  0.]
matrix of shape (2, 3) and value:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


<p>The example above is similar to the first tutorial where we used tf.constant and tf.variable. The importance of having correct tensor shape  can not be over emphasized given that most of the time our errors will be mostly due to incompatible  shape .</p>

<p><b>BROADCASTING</b></p>

<p>
<p>Generally, we  perform element-wise operations (e.g. addition) on tensors of the same shape. In TensorFlow (just as in numpy), however, we mcan perform operations on tensors that would traditionally have been incompatible.</p>

<p> <b>Broadcasting</b> enables TensorFlow to automatically enlarge the smaller array in an operation to be shape compatible for  element-wise operation.</p>
When a tensor gets broadcast, its entries along that dimension get conceptually copied - for optimization purposes.</p>
</p>
For instance, broadcasting enables the following:
If an operand requires a size [7] tensor, a size [1] or a size [ ] tensor can serve as an operand.
If an operation requires a size [7, 10] tensor, any of the following sizes can serve as an operand:
   * `[1, 10]`
   * `[10]`
   * `[]`
   
If an operation requires a size `[10, 13, 19]` tensor, any of the following sizes can serve as an operand:

   * `[1, 13, 19]`
   * `[10, 1, 19]`
   * `[10, 13, 1]`
   * `[1, 1, 1]`
   * `[13, 19]`
   * `[1, 19]`
   * `[19]`
   * `[1]`
   * `[]`   

To illutrate this consider the following example. We will provide example first for 1-Dimen. and then for 2-Dimen. For more on broadcasting visit this link http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc.

In [2]:
with tf.Graph().as_default():
    # Create  vector (1-D tensor).
    matrix = tf.constant([3, 4, 4], dtype=tf.int32)
    print "this example is for ID array,: " ,matrix.shape

    # Create a constant scalar with value 1.
    value1 = tf.constant([4], dtype=tf.int32)
    


    # Add the two tensors. The resulting tensor is a six-element vector.
    evaluation1 = tf.add(value1, matrix)
    

    with tf.Session() as sess:
        print evaluation1.eval()
        

this example is for ID array,:  (3,)
[7 8 8]


In [5]:
with tf.Graph().as_default():
    # Create  matrix (2-D tensor).
    matrix = tf.constant([[3, 4, 4],[3,4,5]], dtype=tf.int32)
    print("2D example case. The shape of matrix is :",matrix.shape)
    print"\n"

    # Create a constant scalar with value 1.
    value1 = tf.constant([[4],[5]], dtype=tf.int32)
    #Note that using value = tf.constant([[1,4],[1,5]], dtype=tf.int32) will give error. Because this is a matrix
    # with its constituents vector. The vector of each row are I-D so we are left with only using one element
    #value2= tf.constant([[1,4],[1,5]], dtype=tf.int32) uncomment 

    # Evaluations
    evaluation1 = tf.add(value1, matrix)
    #evaluation1 = tf.add(value2, matrix)

    with tf.Session() as sess:
        print evaluation1.eval()
        #print evaluation2.eval()
        

('2D example case. The shape of matrix is :', TensorShape([Dimension(2), Dimension(3)]))


[[ 7  8  8]
 [ 8  9 10]]


<p>
From the above note that the size we refer to is different from the number of of element in "each dimension" . It should be clear that in using tf.comstant for the example the values we parse in are the actual elements and not the size.



</p>

<b> Tensor reshaping </b>

<p>When working with tensors it might at times  be necessary to reshape the operands so that a particular operation  ( eg multiplication) can be appllied on them. Reshaping can also help change the rank of a tensor.  </p>

In [53]:
#Illustration to show changing rank of a tensor from vector to matrix


with tf.Graph().as_default():
    # Create a 4-element vector (1-D tensor).
    a = tf.constant([5, 2, 4, 3], dtype=tf.int32)

    # Reshape that 4-element vector into a 2x2 matrix.
    reshaped_version = tf.reshape(a, [2,2])
    

    with tf.Session() as sess:
        print reshaped_version.eval()

[[5 2]
 [4 3]]


In [56]:
#Reshape a tensor so as to enable carrying out operation


with tf.Graph().as_default():
    # Create a 4-element vector (1-D tensor).
    a = tf.constant([5, 2, 4, 3], dtype=tf.int32)
    b = tf.constant([[5, 2],[ 4, 3]], dtype=tf.int32)
    # Reshape b vector into a vector
    reshaped_version = tf.reshape(b, [4])
    multiply = tf.add(reshaped_version,a)
    

    with tf.Session() as sess:
        print multiply.eval()

[10  4  8  6]


In [65]:
with tf.Graph().as_default(), tf.Session() as sess:
    #  operands are initially incompatible for multiplication
   
    a = tf.constant([5, 3, 2, 7, 1, 4])
    b = tf.constant([4, 6, 3])
    # reshape at least one of these operands so that


    # Reshape vector "a" into a 2-D 2x3 matrix:
    reshaped_a = tf.reshape(a, [2,3])

    # Reshape vector "b" into a 2-D 3x1 matrix:
    reshaped_b = tf.reshape(b, [3,1])
    #multiply the operands
    c = tf.matmul(reshaped_a, reshaped_b)
    print(c.eval())



[[44]
 [46]]


## Variables ( Initialisation, Assignment and Storing)


<p>So far, all the concepts we've shown were stateless, they return the same value. TensorFlow `Variable` objects allow you to keep and change state of variables. </p>

<p>When creating a variable, we may use an initial value, or you may use an initializer (like a distribution). This is shown in the example below:</p>

<i> Sample code A </i>

In [129]:

g = tf.Graph()
with g.as_default():
    # Create a variable with the initial value 3
    v = tf.Variable([3], dtype = tf.float32)

    # w is a variable of shape [1], initialised with a random initial value,
    # sampled from a normal distribution with mean 1 and standard deviation 0.35
    w = tf.Variable(tf.random_normal([1], mean=1.0, stddev=0.50)) # 
    w = w.assign(tf.random_normal([1], mean=1.0, stddev=0.50))
    with tf.Session() as sess:
        print "The value of w is : ", sess.run(w)
        print "The value of w is : ", sess.run(w)
        print "The value of w is : ", sess.run(w)

The value of w is :  [ 1.00258064]
The value of w is :  [ 1.01562011]
The value of w is :  [ 0.60514426]


<p><b>Variable initialisation is not automatic</b>. 


<p> We restate again that we  must distinguish between the <b>default values during creation of a variable</b> and <b>the initialisation</b>. Both are necesary. In the above example we used tf.assign for  initialisation.


</p>

Because we use op tf.assign to initialise a variable we will see that running cell <i>Sample code A</i> and the code below will yield different values.
<b>Take away from this : To change the value of a variable use the assign op</b>

----------
# tf.global_variable_initializer( ) 
--------

<p>
<p>The easiest way to initialise a variable is to use <i>tf.global_variable_initializer( )</i> . But the value returned in this case will be constant</p>
</p>

In [130]:
with g.as_default():
    # Create a variable with the initial value 3
    v = tf.Variable([3], dtype = tf.float32)

    # w is a variable of shape [1], initialised with a random initial value,
    # sampled from a normal distribution with mean 1 and standard deviation 0.35
    w = tf.Variable(tf.random_normal([1], mean=1.0, stddev=0.50)) # 
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print (sess.run(w))
        print (sess.run(w))
        print (sess.run(w))

[ 1.48002553]
[ 1.48002553]
[ 1.48002553]


Note the constant value returned below:

In [131]:

with g.as_default():
    sum = tf.add(w,v)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        # These three prints will print the same value.
        print sum.eval()
        print sum.eval()
        print sum.eval()

[ 4.18530846]
[ 4.18530846]
[ 4.18530846]


Using the global initialiser in the same <i>Sample code A</i>

## Comboining tf.global_variables_initializer( )  And Assign


Combining the tf.global_variables_initializer and assign ops  will help simplify our work. In particular we can use the assign op after initialisation with tf.global_variable_initializer( ) to chnage the state of a variable

In [140]:
with g.as_default():
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        # This should print the variable's initial value.
        print "initial value on initialisation: ", v.eval()

        assignment = tf.assign(v, [7])
        # The variable has not been changed yet!
        print "Value before executing the assignment op: ", v.eval()

        # Execute the assignment op.
        sess.run(assignment)
        # Now the variable is updated.
        print "Value after running the assignment op:", v.eval()

initial value on initialisation:  [ 3.]
Value before executing the assignment op:  [ 3.]
Value after running the assignment op: [ 7.]
